spring.application.name=campus-booking-system
spring.datasource.url=jdbc:postgresql://localhost:5432/campus_booking_db
spring.datasource.username=postgres
spring.datasource.password=2426
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true